### PR TITLE
🔧 MAINTAIN: Support `include` parser option in RST

### LINKED ISSUE #388: Add an `eval-myst` directive
maintainer note: you can use https://rst-to-myst.readthedocs.io/ to convert one or more files from RST files -> MyST

----

I was just looking through the Sphinx issues, and saw that [one of the top-rated issues](https://github.com/sphinx-doc/sphinx/issues/7000) included asking how to **include a markdown file in an rST file**.

In the myst-parser, to accomplish the opposite, we suggest users use `eval-rst` to include rST files in their markdown files (https://myst-parser.readthedocs.io/en/latest/using/howto.html#include-rst-files-into-a-markdown-file).

So they can do:

````
# My title

```{eval-rst}
.. include:: myfile.rst
```
````

So perhaps it would also be useful if MyST Parser defined an `eval-myst` directive that could be used within `rST` documents, and could do things like:

````
My title
========

.. eval-myst::

   ```{include} myfile.md
   ```
````

### LINKED ISSUE #417: Is it true MyST-Parser will work on toctree directive, but not on include directive?
### Describe the problem

I wanted to include some link into rst document from md document using MyST parser on sphinx with following attempts (index.rst):

```rst

.. below converts markdown ok

.. toctree::

    links.md

.. below is the only directive that includes text, but without conversion 

.. include:: links.md

.. directives below do not include text

.. include:: links.md
    :parser: myst

.. include:: links.md
    :parser: myst_parser


.. include:: links.md
    :parser: markdown

.. include:: links.md
    :parser: md
```

I was hoping something like 

```
.. include:: links.md
    :parser: myst
```

should convert markdown document to rst and include the rst fragment

### Link to your repository or website

_No response_

### Steps to reproduce

1. Create indext.rst as above
2. Create some file with markdown called link.md
3. `sphinx-build . site`

### The version of Python you're using

_No response_

### Your operating system

_No response_

### Versions of your packages

_No response_

### Additional context

This question seems to suggest chaining of includes: https://stackoverflow.com/questions/46278683/include-my-markdown-readme-into-sphinx

### PR DESCRIPTION
**Pull request by chrisjsewell**
supercedes #414

cc @cpitclaudel

closes #417 
closes #388

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Note, this is not really the intended use case of myst_parser, so I won't be officially supporting it, i.e. if it does not work for whatever reasons, I won't treat that as a bug

**Comment by cpitclaudel** [comment]
Thanks!  

Question about your last comment: is building with Sphinx the only supported use case, or is the plan to also support building with the standard Docutils pipeline? (or in fact with other programs that build on top of it, like Pelican?)

The reason I'm asking is that I use the standard Docutils pipeline in plenty of places, and I wouldn't be against migrating these documents to Markdown — but I want to make sure that things aren't going to break unexpectedly.

**Comment by choldgraf** [comment]
Cc @damianavila who was playing around with getting Myst to work in Nikola

**Comment by cpitclaudel** [comment]
I think we would be super nice to be able to use MyST with docutils — the way reCommonMark can be used and through the usual methods in `docutils.core`.  This parser is a great step in this direction, and I've opened a related feature request at https://github.com/executablebooks/MyST-Parser/issues/420

**Pull request merged**
