### PR TITLE
📚 DOCS: Add the sphinx-tippy extension

### PR DESCRIPTION
**Pull request by chrisjsewell**
Inspired by @rowanc1, I created https://sphinx-tippy.readthedocs.io 😄

### CODE REVIEW

**Comment by rowanc1** [comment]
Oh wow, that is super cool to see this functionality making it's way into sphinx. Are you doing all/most of this at compile time?

**Comment by chrisjsewell** [comment]
>  Are you doing all/most of this at compile time?

yeh I've implemented it to do it all at compile time, so I don't have to deal with CORS, caching, etc 😅 

although, as mentioned https://sphinx-tippy.readthedocs.io/en/latest/#how-does-it-work, there is also https://sphinx-hoverxref.readthedocs.io/ that RTD guys run that requires you be running the website with them hosting

**Comment by rowanc1** [comment]
Yeah, makes sense. Certainly difficult to do without a service running.

**Comment by chrisjsewell** [comment]
yeh was just interested to see how/what could be done statically

**Comment by chrisjsewell** [comment]
Ah RTD also has a content API: https://readthedocs.org/api/v3/embed/?url=https://myst-parser.readthedocs.io/en/latest/intro.html%23get-started

**Comment by chrisjsewell** [comment]
> Ah RTD also has a content API

@rowanc1 I guess this type of content API, returning HTML, isn't ideal though, because you are then going to apply your local CSS which might not be "compatible"

**Pull request merged**
