### PR TITLE
🔧 MAINT: pin sphinxcontrib-bibtex & fix deprecated doc config

### PR DESCRIPTION
**Pull request by lesteve**
Bump into this in #274 so pinning as mentioned in https://github.com/executablebooks/MyST-Parser/pull/274#issuecomment-748017517.

### CODE REVIEW

**Comment by lesteve** [comment]
The error was a warning about expand_sections which seems to have been removed from sphinx-book-theme: https://github.com/executablebooks/jupyter-book/pull/1073

**Comment by choldgraf** [comment]
@lesteve perfect -- thanks for the pin and for catching the issue with sphinx-book-theme :-) I suppose we should probably be following our own deprecation patterns shouldn't we ;-)

This looks great to me, thanks very much!

**Comment by lesteve** [comment]
> I suppose we should probably be following our own deprecation patterns shouldn't we ;-)

I guess having multiple repos makes it more likely that one will slip through the cracks :wink:

**Comment by choldgraf** [comment]
you have no idea haha

**Comment by choldgraf** [comment]
actually, you probably do :-)

**Pull request merged**
