### PR TITLE
Fix a rendering issue in the API docs

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by choldgraf** [comment]
nice! thanks for catching this

**Comment by asmeurer** [comment]
I was trying to see if I could figure out #164. I think I see bits and pieces of what needs to be done, but overall it might be simpler if someone who already knows the code fixes it.

**Comment by choldgraf** [comment]
I added a quick comment that points to where I think the relevant code is in recommonmark, maybe that can also help point the right direction?

**Comment by asmeurer** [comment]
Actually I don't need it anymore, so I have less motivation to do it ;)

The only reason I wanted it was #179 and it isn't even clear to me if #164 would fix that.

**Pull request merged**
