### PR TITLE
✨ NEW: Add `myst_title_to_header` configuration

### PR DESCRIPTION
**Pull request by chrisjsewell**
This is the "simplest" implementation (3 extra lines!).

Basically, it treats this:

```markdown
---
title: "A **title**"
---
```

like this (including parsing nested syntax)

```markdown
# A **title**
```

I'm not sure if this would be the correct/expected implementation though

for example, currently

```markdown
---
title: "A **title**"
---

# Another title
```

would be treated as

```markdown
# A **title**

# Another title
```

but should it instead be treated as

```markdown
# A **title**

## Another title
```

(also, on a technical note, the parsing should be a bit smarter, in only allowing inline syntax,
there should probably also be a config to turn it off/on)

### CODE REVIEW

**Comment by choldgraf** [comment]
Agree with the implementation + your assessment of where it might be confusing. I think it'd be great if specifying `title:` also bumped all other headers on the page down one level. However if the implementation is complex, then just this PR as it already stands would be an improvement I think

**Comment by chrisjsewell** [comment]
I think it would be good to check what the behaviour of e.g. pandoc is on this, then just copy that. If even a little more complex, it should be possible either way

**Comment by chrisjsewell** [comment]
> behaviour of pandoc

See https://pandoc.org/MANUAL.html#metadata-blocks

>  when the `--standalone` (`-s`) option is chosen .. The title in the body appears as an H1 element

`test.md`
```markdown
---
title: A **title**
---

# Header

```

```console
$ pandoc -s test.md
...
<body>
<header id="title-block-header">
<h1 class="title">A <strong>title</strong></h1>
</header>
<h1 id="header">Header</h1>
</body>
```

i.e. the `title` is parsed as Markdown, and does not affect subsequent headings

**Comment by chrisjsewell** [comment]
Ok good to go, if you agree @choldgraf, @rowanc1

**Comment by rowanc1** [comment]
Looks good to me! Good to notice the option for this, and updating the docs!

**Comment by chrisjsewell** [comment]
> Looks good to me! Good to notice the option for this, and updating the docs!

Cheers!

Note, with the recent updates I've made, it would actually be quite easy to set a "header level offset", i.e. to turn every `#` into `##` etc.
But as discussed, this is not the behaviour of pandoc (and thus also quarto) plus, as noted by @choldgraf (https://github.com/executablebooks/meta/discussions/615#discussioncomment-1921714)

> Markdown tends to map `#` to `<h1>` and `##` to `<h2>`

which I agree is easy for users to understand.

So I think the current behaviour is correct and no offset is needed

**Pull request merged**
