### PR TITLE
♻️ REFACTOR: Parsing logic of Markdown links

### PR DESCRIPTION
**Pull request by chrisjsewell**
This PR aims to clarify and improve the parsing of Markdown links, i.e. `[Text](link)`

Related issues: #193, #402, #411, #435

## Current logic

1. For both docutils and sphinx, if the link starts with a scheme prefix (e.g. `http:`) and that scheme is in `myst_url_schemes` or `myst_url_schemes=None`, then create an external link, e.g. `<a href="http://example.com">Text</a>
2. For both docutils and sphinx, if the link contains a `#` (i.e. a fragment), then also create an external link (unless the `heading_anchors` extension is active)
3. If docutils, and neither of the above, then nothing is rendered, and a warning is raised for a missing reference
4. If sphinx, and neither of the above, then create a sphinx node `addnodes.pending_xref` of type "myst"

After (4), the "myst" `pending_xref` are then intercepted in the `MystReferenceResolver` post-transform (after all documents have been parsed), and the reference resolved similar to the sphinx [`any` role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any):
They check the reference against all reference types, taking the first hit as the target and emitting a warning, if none or multiple targets are found.
Different to the standard `any` role sphinx `ReferenceResolver`, the myst one allows for (a) matching document paths with their extensions, e.g. `[Text](path/to/other.md)`, and (b) parsing nested syntax as part of the text, e.g. `[Text **bold**](link)`.

there is also a little more complication, when using the `heading_anchors` extension, to match generated header targets, e.g. `[Text](document.md#header-1)`

## Shortcomings

(2) I believe originally came from recommonmark, but I think it is probably too permissive and unexpected.

(3) Is definitely not ideal, for docutils only use

(4) What is currently not handled, is links to "non-sphinx" files, e.g. non RST or Markdown files like `[Text](path/to/file.txt)`. In sphinx we would want to use the `download` role for this, to ensure that the referenced files are copied into the build directory and the end `href` points to that.

## Current Improvements

This PR is in draft, but current improvements are:

- Add a configuration `myst_all_links_external=True`, which simply directs for all links to be rendered as external links.
  I think this can be helpful for especially docutils use
- Remove step (2)
- For step (3) create a docutils internal link
- In step (4), if the link matches a "non-sphinx" file path, then create a `download_reference` node.

Perhaps there can be some more configuration,
but one thing I want to balance is (a) having sensible defaults, (b) allowing for some configuration, but (c) not having too much allowed configuration, which would be confusing to basic users and also then need to be replicated in any future MyST parser implementations.

## Questions

- Is it a problem to remove (2); no longer assuming links with `#` are external links?

I'll expand on this a bit more at a later data, but welcome comments from interested parties: @choldgraf, @mmcky, @rowanc1, @cpitclaudel, etc

### CODE REVIEW

**Comment by choldgraf** [comment]
This sounds pretty reasonable to me. This sounds like a nice improvement. A few thoughts:

- Agree that `#2` feels like we are trying to make too many assumptions on the user's behalf.
- Agree that when people link directly to a file, the right behavior to assume is the `{download}` role
- Presumably `myst_all_links_external=True` defaults to `False`, at least for when we're in a Sphinx context?

**Comment by chrisjsewell** [comment]
> Presumably myst_all_links_external=True defaults to False, at least for when we're in a Sphinx context?

yes, `myst_all_links_external` default is `True`

**Comment by chrisjsewell** [comment]
See full documentation: https://myst-parser--467.org.readthedocs.build/en/467/syntax/syntax.html#markdown-links-and-referencing

**Comment by choldgraf** [comment]
👍

**Comment by mmcky** [comment]
thanks @chrisjsewell -- I think this is a nice improvement. 

I particularly like that links to non-source documents are migrated to download links. I think that is nice behaviour. 👍

**Comment by unparalleled-js** [comment]
I used to be able to link to local HTML (post-build) files but it seems that is no longer the case?

**Pull request merged**
