### PR TITLE
📚 DOCS: Refactoring and updating documentation

### LINKED ISSUE #383: Documentation re-structure proposal
# Background

The MyST Parser has grown quite a lot in adoption, extended syntax, and has the potential to begin diversifying into other non-Sphinx parsing use-cases as well (e.g., Javascript, Nikola, etc).

I think that it'd be easier for people to find the usecase-specific information they need about MyST if we re-structured the documentation a little bit. I think a main goal should be to separate the MyST core specification from the Sphinx-specific functionality. That way it's clearer to others how they could use MyST in a non-Sphinx context, and should be clearer where *new* documentation should go when we add it in the future.

# A proposed structure

I'd imagine a high-level structure similar to the [Diataxis framework](https://diataxis.fr/) with the following major sections:

- Tutorials
  - Get started with MyST in Sphinx <-- tutorial focused on using MyST with Sphinx
  - (future tutorials could cover more usecase-specific things like substitutions, or developer tutorials like "write your own MyST parser")
- Topic Guides
  - MyST Markdown Syntax <-- parser-agnostic MyST syntax, no Sphinx-specific features in here
    - Core Syntax Guide
    - Extended Syntax Guide
    - Syntax Reference
  - MyST in Sphinx <-- focuses on Sphinx-specific functionality of the MyST Parser
    - MyST behavior that is unique to Sphinx (e.g., `[]()` link syntax as a short-hand for `{any}` role)
    - Explanations about relationship between MyST/rST/Sphinx
  - Parse with the Python API <-- focuses on MyST from a developer's perspective. Could include discussion of `markdown-it-py` as well.
- About MyST  <-- "meta" categories about the project itself
  - Contributing
  - Changelog

Does this seem like a reasonable separation of functionality and topics? Does it seem straightforward to extend and grow moving forward?

### PR DESCRIPTION
**Pull request by choldgraf**
This PR overhauls much of the MyST documentation, with the following goals:

- Separate out the "Sphinx extension", "MyST Specification", and "Python API" parts of this package more cleanly
- Take inspiration from the [diataxis framework](https://diataxis.fr/) for structuring our content
- Provide a bit more explanation etc around our various examples
- Add a "getting started tutorial" that is more like a step-by-step guide to using MyST in Sphinx.

My hope is that this will overall make the documentation easier to discover/parse, understand, and potentially extend in the future as we wish to add more information.

Note that there is still a lot of improvement we could make to the documentation, but I wanted to leave it here as a mostly "structural change" and we can discuss ways to improve it further in the future.

closes #383 

ping to @damianavila as well, perhaps he has thoughts on whether this structure would make it easier for newcomers to understand MyST and the various ways one can use it.

Probably the easiest way to review this is to just look at the built docs preview: https://myst-parser--385.org.readthedocs.build/en/385/

### CODE REVIEW

**Comment by damianavila** [comment]
> ping to @damianavila as well, perhaps he has thoughts on whether this structure would make it easier for newcomers to understand MyST and the various ways one can use it.

I think this is a great start. 
1. I would probably put the "Discussion and explanation" as the first topic guide.
2. What do you think about putting the "Contribute to MyST" into the topic guide as well (as the last item on that section)?

**Comment by chrisjsewell** [comment]
thanks looking good, but quick comment of the bat; I think the landing page is still a bit to busy. I want to see clear routes for users, e.g.:

- I have existing Markdown files that I want to turn in to a website/documentation
- I have documentation in RST but would like to migrate to Markdown

I would consider using panels

**Comment by choldgraf** [comment]
Thanks for the suggestions @chrisjsewell and @damianavila - I've made another update on the main page and re-structured according to @damianavila's suggestions. I've replace most of the front-page content with a 6-panel layout. WDYT?

Here's a screenshot below:

image

**Comment by damianavila** [comment]
> I've replace most of the front-page content with a 6-panel layout. WDYT?

I like that!

Btw, I do not see the second set of panels in this PR, am I missing something or you did not push it?

**Comment by choldgraf** [comment]
Hmm I may have mis-pushed something. will investigate when I'm back at a computer

**Comment by choldgraf** [comment]
OK this PR is now updated and ready for another look @chrisjsewell and @damianavila. if people don't think there's anything really problematic with this PR, I am also happy to merge this relatively quickly, and keep iterating on the docs in subsequent PRs otherwise we're gonna hit a bunch of merge conflicts.

**Comment by chrisjsewell** [comment]
thanks @choldgraf, I'll give a review today/tomorrow

**Review by damianavila — DISMISSED** [review]
A quick overview of the changes and the final result looks OK to me.

**Comment by choldgraf** [comment]
I've rebased on master since the latest merges introduced a bunch of conflicts. I think this is ready to go unless folks have major problems they see with it.

**Comment by damianavila** [comment]
I still see some conflicts on this branch accordingly to GitHub UI.

**Comment by choldgraf** [comment]
oops - yep, that is resolved now too (that was from another #393 )

**Comment by choldgraf** [comment]
(I will merge this in an hour or so unless somebody wants to see some more changes, I'm giving a talk today and wanna plug myst :-) happy to spot check more improvements to the docs in subsequent PRs)

**Comment by chrisjsewell** [comment]
Cheers

**Pull request merged**
