### PR TITLE
👌 Change non-fatal directive parsing errors to warnings

### PR DESCRIPTION
**Pull request by chrisjsewell**
For non-fatal errors, such as;
faulty options syntax, unknown option keys, and invalid option values,
a warning is raised, but the directive is still run (without the erroneous options).
The warning is given the `myst.directive_parse` type, which can be suppressed.

### CODE REVIEW

**Comment by rowanc1** [comment]
Very much want to see this in the JS side as well, it is a bit too strict.

**Comment by rowanc1** [comment]
I only looked at the tests, but this seems like a great addition to me 👍. I will follow suit in the JS side soon!

**Comment by chrisjsewell** [comment]
> Very much want to see this in the JS side as well, it is a bit too strict.

yep exactly, I know we talked about this

Either in this PR or a follow, was going to add changing unknown directives and roles to a warning, with a certain warning type

**Comment by rowanc1** [comment]
Awesome, can you tag me so I can make the JS one the same!

**Comment by choldgraf** [comment]
> was going to add changing unknown directives and roles to a warning, with a certain warning type

+1 from me

**Pull request merged**
