### PR TITLE
Revert "🚀 RELEASE: v0.12.10"

### PR DESCRIPTION
**Pull request by choldgraf**
Reverts executablebooks/MyST-Parser#256

### CODE REVIEW

**Comment by chrisjsewell** [comment]
wait what you doing? don't commit a revert, just delete the release

**Comment by choldgraf** [comment]
don't we want the latest github releases to match our master branch? I figure we wouldn't want them to diverge because I dunno how to fix this pypi bug

**Comment by choldgraf** [comment]
(and btw I was just gonna mention, I don't think I have the permissions to delete a release? for some reason the delete button wasn't there for me)

**Comment by chrisjsewell** [comment]
lets just work out the issue before unnecessary reverts

**Comment by choldgraf** [comment]
if that's what you prefer that's fine with me - I'm just used to the opposite - "revert immediately and then work out the issue" 🤷‍♂️

**Comment by chrisjsewell** [comment]
The release is still the release though, the code is not going to change. Anyway this is the issue: https://github.com/pypa/warehouse/issues/8565, so its just a matter of waiting for a fix

**Comment by choldgraf** [comment]
looks like it's been reverted, not sure when that gets pushed to prod though: https://github.com/pypa/warehouse/pull/8591

**Comment by chrisjsewell** [comment]
No it seems like they fixed it, then promptly broke it again lol: https://github.com/pypa/warehouse/issues/8565#issuecomment-696411651

**Comment by choldgraf** [comment]
I think that revert fixed it (hopefully), it was just merged 10 minutes ago

**Comment by choldgraf** [comment]
I just restarted https://github.com/executablebooks/MyST-Parser/runs/1146660092?check_suite_focus=true - lets see if they deployed it

**Comment by choldgraf** [comment]
erm nevermind, I think you deleted the tag again

**Comment by chrisjsewell** [comment]
its done

**Comment by choldgraf** [comment]
nice

**Pull request closed without merging**
