### PR TITLE
⬆️ Drop sphinx 4 support, add sphinx 6

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by lorengordon** [comment]
Any plans to create a new release that includes this support?

**Comment by RCheesley** [comment]
@chrisjsewell will there be a release at some point soon? It's blocking us from updating several dependencies at the moment. I checked the milestones but it looks a little out of date, so would be super helpful to know if you're maybe working to a timeline for the next release?

**Comment by chrisjsewell** [comment]
> Any plans to create a new release that includes this support?

Nearly there, should be just: #695 and #696

**Comment by RCheesley** [comment]
That's great, anything we can do to help get them over the line?

**Pull request merged**
