### PR TITLE
⬆️  UPGRADE: Change Sphinx pinning to allow version 4

### PR DESCRIPTION
**Pull request by astrojuanlu**
Sphinx 4.0.0b2 beta is out, and it would be great to see if MyST-Parser works with it. I am doing some local tests with https://github.com/poliastro/poliastro/, which uses it.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
thanks, but I can say for definite there are things to address like https://github.com/executablebooks/meta/issues/306#issuecomment-827681278

**Comment by astrojuanlu** [comment]
Woops, I didn't see that discussion, will take a look. Thanks @chrisjsewell!

**Comment by jpmckinney** [comment]
Can we unpin and later fix mathjax issues? Not everyone who uses MyST-Parser (but who wants to use Sphinx 4) uses mathjax. It can be a minor version to flag that the upgrade isn't seamless.

**Comment by chrisjsewell** [comment]
superceded by #390

**Pull request closed without merging**
