### PR TITLE
:sparkles: NEW: Emits sphinx include-read event

### LINKED ISSUE #881: Emit include-read event
### Describe the feature you'd like to request

Sphinx added an [include-read](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-include-read) event with 7.2.5 that is emitted after an include directive is processed. 
It would be helpful to implement that for the MyST include directive too.

### Describe the solution you'd like

The "include-read" event could be emitted immediately after the file is read [like Sphinx does it](https://github.com/sphinx-doc/sphinx/blob/ae51974e217cc7590e1b9c68f18af3e043027c6d/sphinx/directives/other.py#L400-L403).

Maybe adding this in [MockIncludeDirective](https://github.com/executablebooks/MyST-Parser/blob/master/myst_parser/mocking.py#L382) is good enough? 
```py
# Emit the "include-read" event
arg = [file_content]
self.renderer.sphinx_env.app.events.emit("include-read", path, self.renderer.sphinx_env.docname, arg)
file_content = arg[0]
```

### Describe alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by sumezulike**
Adds emission of Sphinx `include-read` events while processing include directives, closes #881.

[include-read](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-include-read)

If there is a better way to restrict the test to Sphinx>=7.5.2, please let me know.

### CODE REVIEW

**Comment by sumezulike** [comment]
Sorry about the noise, I forgot to test against older Python versions. Grateful for any feedback!

**Comment by chrisjsewell** [comment]
cheers will have a look soon

**Comment by sumezulike** [comment]
Any chance to take a look yet?

**Comment by chrisjsewell** [comment]
> If there is a better way to restrict the test to Sphinx>=7.5.2, please let me know.

sorted

**Review by chrisjsewell — APPROVED** [review]
all good thanks!

**Comment by sumezulike** [comment]
Awesome, thanks!

**Pull request merged**
